### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by garystafford** [atom/whitespace#105]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package, v0.32.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:448:29)
    at TextBuffer.module.exports.TextBuffer.getEndPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:954:38)
    at TextBuffer.module.exports.TextBuffer.getRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:936:54)
    at TextBuffer.module.exports.TextBuffer.backwardsScan (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:864:52)
    at Whitespace.module.exports.Whitespace.removeTrailingWhitespace (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:112:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:58:21
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:798:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1038:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:23)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:452:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:641:35)
    at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:680:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:170:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:18.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "build-gradle",
      "bottom-dock",
      "gradle-manager"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
autocomplete-ruby, v0.1.0
build, v0.52.0
color-picker, v2.0.14
jade-beautify, v0.0.11
language-chef, v0.8.0
language-gradle, v0.0.3
language-groovy, v0.4.0
linter, v1.11.3
linter-foodcritic, v0.5.1
linter-js-yaml, v1.2.5
linter-manager, v0.2.8
linter-rubocop, v0.4.5
linter-ruby, v1.2.0
minimap-git-diff, v4.1.8
nucleus-dark-ui, v0.7.3
pretty-json, v0.4.1
ruby-block, v0.3.5
travis-ci-status, v0.18.0
tree-view-bundler, v0.0.3
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by sryze** [comment]
Same problem here, with Atom 1.5.3 (OS X 10.11.3):

```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:457:29)
    at Object.<anonymous> (/Users/sergey/.atom/packages/linter-jshint/lib/main.js:138:57)
    at [object Generator].next (native)
    at step (/Users/sergey/.atom/packages/linter-jshint/lib/main.js:3:273)
```
