### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by lsenta** [atom/whitespace#153]
Hi there,
here's the steps to reproduce the error:
install proto-repl, start a repl, press backspace in the repl a couple of time.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package 0.36.2

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

TypeError: Cannot read property 'start' of undefined
    at /app.asar/node_modules/whitespace/lib/whitespace.js:114:43
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/text-editor.js:1127:25
    at /app.asar/src/text-editor.js:1161:28
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/text-editor.js:1155:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2568:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2534:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1153:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1119:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/app.asar/src/text-editor.js:1134:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at /app.asar/src/register-default-commands.js:606:21)
    at /app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1594:26)
    at /app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -6:33.9.0 proto-repl:remote-nrepl-connection (ul.list-inline.tab-bar.inset-panel)
     -6:30.3.0 core:backspace (input.hidden-input)
     -6:29.7.0 core:confirm (input.hidden-input)
     -6:29.4.0 editor:newline (input.hidden-input)
     -6:27.8.0 core:backspace (input.hidden-input)
  2x -6:27.3.0 proto-repl:execute-text-entered-in-repl (input.hidden-input)
     -6:16.8.0 core:paste (input.hidden-input)
  4x -6:16.4.0 proto-repl:execute-text-entered-in-repl (input.hidden-input)
     -0:08.1.0 editor:newline (input.hidden-input)
     -0:07.5.0 proto-repl:execute-text-entered-in-repl (input.hidden-input)
  3x -0:06.4.0 core:backspace (input.hidden-input)
     -0:05.5.0 proto-repl:execute-text-entered-in-repl (input.hidden-input)
  2x -0:05.2.0 core:backspace (input.hidden-input)
     -0:04.2.0 core:move-up (input.hidden-input)
  3x -0:03.8.0 core:backspace (input.hidden-input)
  5x -0:03.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
proto-repl 1.4.20 
```

**Comment by maxbrunsfeld** [comment]
Can you update to the latest Atom (Atom 1.18 or 1.19.0-beta0) and report whether this still happens?
