### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by andronat** [atom/whitespace#71]
Sorry I have no idea how this came up. I just pressed save and suddenly... 

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package, v0.29.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1040:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:174:33)
  at new Marker (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:34:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1265:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1280:24
  at Array.map (native)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarkers (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1276:39)
  at DisplayBuffer.module.exports.DisplayBuffer.refreshMarkerScreenPositions (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1397:20)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:304:14)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1473:19)
  at Fold.module.exports.Fold.updateDisplayBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:90:35)
  at Fold.module.exports.Fold.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:98:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:20:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:249:20)
  at Fold.module.exports.Fold.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:43:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/fold.js:28:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:380:27)
  at MarkerStore.module.exports.MarkerStore.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:223:32)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:691:24)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:974:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:967:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:567:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:314:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
  8x -1:35.9.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:34.6.0 core:copy (atom-text-editor.editor.is-focused)
  5x -1:30.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:29.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:28.9.0 core:paste (atom-text-editor.editor.is-focused)
     -1:23.7.0 core:copy (atom-text-editor.editor.is-focused)
  3x -1:22.5.0 core:paste (atom-text-editor.editor.is-focused)
     -1:10.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:10 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:09.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:07.4.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -1:06.7.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:05.6.0 core:select-up (atom-text-editor.editor.is-focused)
     -1:05.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:04.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:03.8.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-php",
      "language-perl",
      "language-mustache",
      "language-less",
      "language-html",
      "language-css",
      "language-coffee-script",
      "language-c",
      "language-clojure",
      "language-objective-c"
    ]
  },
  "whitespace": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
go-plus, v3.3.11
linter, v0.12.6
linter-pep257, v0.2.1
linter-pep8, v0.2.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports in 2 years, closing.
