### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by alexszilagyi** [atom/whitespace#79]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package, v0.30.0
### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:762

TypeError: Cannot read property 'scopeName' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:58:73
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:985:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:311:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
  8x -2:03.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:51.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -1:51 core:save (atom-text-editor.editor.is-focused)
     -1:35.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:34.8.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:34.1.0 core:delete (atom-text-editor.editor.is-focused)
  4x -1:33.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:32.9.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -1:27.5.0 core:delete (atom-text-editor.editor.is-focused)
     -1:25.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:24.9.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -1:24.7.0 core:move-right (atom-text-editor.editor.is-focused)
  5x -1:23.5.0 core:delete (atom-text-editor.editor.is-focused)
  9x -1:22 core:save (atom-text-editor.editor.is-focused)
  2x -0:57.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:09.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
language-smarty-php, v0.5.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@alexszilagyi, what were you doing when this error occured?  If you can reproduce it consistently, does it still happen in safe mode (`atom --safe`)?  Thanks.

**Comment by 50Wliu** [comment]
No response; no further reports in two years.
