### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by filipvanreeth** [atom/whitespace#85]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package, v0.30.0
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

TypeError: Cannot read property 'match' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:669:23)
    at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:663:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.retokenizeWhitespaceRowsIfIndentLevelChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:409:69)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:387:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
```
### Commands

```
     -0:28.7.0 project-manager:toggle (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:09.3.0 csscomb:run (atom-text-editor.editor.is-focused)
     -0:05.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:05.1.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "livereload",
      "atom-terminal",
      "terminal-status",
      "atom-beautify",
      "aligner-php",
      "aligner",
      "autocomplete-php",
      "grunt-runner",
      "wordpress-api",
      "atom-wordpress",
      "linter-htmlhint",
      "linter-php",
      "linter-tidy",
      "merge-conflicts",
      "remote-sync"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
csscomb, v0.3.1
emmet, v2.3.12
file-icons, v1.5.8
linter, v1.2.4
linter-scss-lint, v1.0.5
minimap, v4.12.0
project-manager, v1.15.11
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
No further reports in two years, closing.
