### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Alhadis** [atom/whitespace#98]
[Enter steps to reproduce below:]

1. Was converting a 114645-line XML file to hard tabs (it was indented with 2-spaces each, ffs)

**Atom Version**: 1.1.0  
**System**: Mac OS X 10.9.5  
**Thrown From**: [whitespace](https://github.com/atom/whitespace) package, v0.31.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

~~~
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:108

RangeError: Maximum call stack size exceeded
  at History.module.exports.History.groupChangesSinceCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/history.js:109:41)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:776:20)
  at Whitespace.module.exports.Whitespace.convertSpacesToTabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:178:21)
  at atom-workspace.Whitespace.subscriptions.add.atom.commands.add.whitespace:convert-spaces-to-tabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:36:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

~~~

### Commands

~~~
-0:01.3.0 application:new-file (atom-text-editor.editor.is-focused)
-0:01.3.0 core:paste (atom-text-editor.editor.is-focused)
~~~

### Config

~~~ json
"core": {
	"themes": [
		"atom-light-ui",
		"phoenix-syntax"
	],
	"disabledPackages": [
		"snippets",
		"SFTP-deployment",
		"spell-check",
		"autocomplete-css",
		"autocomplete-plus",
		"compare-files",
		"merge-conflicts",
		"atom-compare-files",
		"background-tips",
		"welcome"
	]
},
"whitespace": {
	"removeTrailingWhitespace": false
}
~~~

### Installed Packages

~~~ shell
# User
Sublime-Style-Column-Selection, v1.3.0
asciidoc-preview, v0.6.0
atom-beautify, v0.28.16
auto-detect-indentation, v0.4.2
editorconfig, v1.2.0
file-icons, v1.6.11
hex, v0.6.2
language-antlr, v0.1.0
language-apache, v1.3.0
language-asciidoc, v0.12.0
language-fortran, v2.0.4
language-haskell, v1.4.12
language-latex, v0.6.1
language-x86, v0.1.0
project-manager, v2.6.5

# Dev
No dev packages
~~~

**Comment by Alhadis** [comment]
No longer reproducible or relevant. Original issue was never observed a second time since filing this issue.
